clearth-modules/clearth-gui/src/main/java/com/exactprosystems/clearth/web/beans/ClearThCoreApplicationBean.java
/******************************************************************************
 * Copyright 2009-2023 Exactpro Systems Limited
 * https://www.exactpro.com
 * Build Software to Test Software
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/

package com.exactprosystems.clearth.web.beans;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.exactprosystems.clearth.ClearThCore;
import com.exactprosystems.clearth.ConfigFiles;
import com.exactprosystems.clearth.DeploymentConfig;
import com.exactprosystems.clearth.utils.ClearThException;
import com.exactprosystems.clearth.utils.MemoryAndSpaceMonitor;
import com.exactprosystems.clearth.web.WebDeploymentConfig;
import com.exactprosystems.clearth.web.jetty.JettyXmlUpdater;

public abstract class ClearThCoreApplicationBean
{
	private static final Logger logger = LoggerFactory.getLogger(ClearThCoreApplicationBean.class);
	
	private static ClearThCoreApplicationBean appInstance = null;
	
	protected DeploymentConfig deploymentConfig = null;
	protected ConfigFiles configFiles = null;
	
	private Exception initializationError = null;
	private String appContextPath;
	private boolean appContextPathOverride;
	
	public ClearThCoreApplicationBean() throws ClearThException
	{
		synchronized (ClearThCoreApplicationBean.class)
		{
			if (appInstance != null)
				throw new ClearThException("ApplicationBean already created");
			
			appInstance = this;
			
			try
			{
				configFiles = createConfigFiles();
				deploymentConfig = createDeploymentConfig();
				deploymentConfig.init(configFiles);
				initApplication();
				initWebApplication();
			}
			catch (Exception e)
			{
				initializationError = e;
				logger.error("Error while initializing application", e);
			}
		}
	}

	protected abstract void initApplication() throws ClearThException;
	protected abstract ConfigFiles createConfigFiles();
	
	
	public static ClearThCoreApplicationBean getInstance()
	{
		return appInstance;
	}
	
	
	public String getAppContextPath()
	{
		return appContextPath;
	}
	
	public boolean isAppContextPathOverride()
	{
		return appContextPathOverride;
	}
	
	public Exception getInitializationError()
	{
		return initializationError;
	}
	
	public String getInitializationErrorText()
	{
		Exception error = getInitializationError();
		if (error == null)
			return null;
		
		String result = error.getMessage();
		if (error.getCause() != null)
		{
			if (!result.endsWith("."))
				result += ".";
			result += " "+error.getCause().getMessage();
		}
		return result;
	}
	
	public String getUsedMemoryInfo()
	{
		return String.valueOf(MemoryAndSpaceMonitor.getUsedMemoryMb());
	}
	
	public String getMaxMemoryInfo()
	{
		return String.valueOf(MemoryAndSpaceMonitor.getMaxMemoryMb());
	}
	
	public String getUsedSpaceInfo()
	{
		return String.valueOf(MemoryAndSpaceMonitor.getUsedSpace(MemoryAndSpaceMonitor.GB_FACTOR));
	}
	
	public String getTotalSpaceInfo()
	{
		return String.valueOf(MemoryAndSpaceMonitor.getTotalSpace(MemoryAndSpaceMonitor.GB_FACTOR));
	}
	
	public boolean isMemoryBreachesLimit()
	{
		return MemoryAndSpaceMonitor.isMemoryBreachLimit(90);
	}
	
	
	protected void initWebApplication() throws ClearThException
	{
		WebDeploymentConfig webDeploymentConfig = (WebDeploymentConfig) deploymentConfig;
		this.appContextPath  = webDeploymentConfig.getAppContextPath();
		this.appContextPathOverride = webDeploymentConfig.isAppContextPathOverride();
		
		updateJettyXml(ClearThCore.rootRelative("jetty/etc/jetty.xml"));
	}
	
	protected void updateJettyXml(String jettyXmlPath)
	{
		JettyXmlUpdater xmlUpdater = initJettyXmlUpdater();
		xmlUpdater.updateJettyXml(jettyXmlPath);
	}
	
	protected JettyXmlUpdater initJettyXmlUpdater()
	{
		return new JettyXmlUpdater();
	}
	
	protected DeploymentConfig createDeploymentConfig()
	{
		return new WebDeploymentConfig();
	}
}

clearth-modules/clearth-gui/src/main/java/com/exactprosystems/clearth/web/beans/UserBean.java
/******************************************************************************
 * Copyright 2009-2019 Exactpro Systems Limited
 * https://www.exactpro.com
 * Build Software to Test Software
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/

package com.exactprosystems.clearth.web.beans;

import com.exactprosystems.clearth.utils.DateTimeUtils;
import com.exactprosystems.clearth.web.misc.UserInfoUtils;

public class UserBean extends ClearThBean
{
	public String getUserName()
	{
		return UserInfoUtils.getUserName();
	}
	
	public String getRole()
	{
		return UserInfoUtils.getUserRole();
	}
	
	public boolean isLoggedIn()
	{
		return UserInfoUtils.isLoggedIn();
	}
	
	public boolean isAdmin()
	{
		return UserInfoUtils.isAdmin();
	}
	
	public boolean isPowerUser()
	{
		return UserInfoUtils.isPowerUser();
	}
	
	public boolean isRegularUser()
	{
		return UserInfoUtils.isRegularUser();
	}
	
	public boolean isNewYear()
	{
		return DateTimeUtils.isNewYear();
	}
}

clearth-modules/clearth-gui/src/main/webapp/ui/login.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
		xmlns:ui="http://java.sun.com/jsf/facelets"
		xmlns:h="http://java.sun.com/jsf/html"
		xmlns:f="http://java.sun.com/jsf/core"
		xmlns:p="http://primefaces.org/ui"
		template="../templates/ui.xhtml">
	
	<ui:define name="title">Login</ui:define>
	
	<f:metadata>
		<f:viewParam name="requestUrl" value="#{authBean.requestUrl}" />
		<f:event type="preRenderView" listener="#{authBean.pullValuesFromFlash}"/>
	</f:metadata>
	
	<ui:define name="page">
		<div id="loginContainer">
			<h:form id="loginPanel" rendered="#{ApplicationBean.initializationError == null}">
				<div id="#{!userBean.newYear ? 'cthLogo' : 'cthLogoNY'}" />
				<p:focus context="loginPanel" />
				<p:inputText id="userName" styleClass="authorizeField" value="#{authBean.userName}" autocomplete="off" />
				<p:watermark for="userName" value="Username" />
				<p:password id="password" styleClass="authorizeField" value="#{authBean.password}" feedback="false" />
				<p:watermark for="password" value="Password" />
				<p:commandButton styleClass="loginButton" value="Sign in" action="#{authBean.login}"
						ajax="false" update="loginPanel" />
				<p:messages id="msg" for="loginError" styleClass="loginError" showSummary="false" showDetail="true" />
				<p:effect type="drop" event="load" for="msg" delay="5000">
					<f:param name="mode" value="'hide'" />
					<f:param name="direction" value="'up'" />
				</p:effect>
			</h:form>
			<p:outputPanel id="fatalError" rendered="#{ApplicationBean.initializationError != null}">
				<h:outputText value="#{ApplicationBean.initializationErrorText}" />
			</p:outputPanel>
			<h:form>
				<p style="margin-top: 0px" id="copyright">&copy; 2011-2023 Exactpro Systems, LLC<span style="margin-left: 10px;"><h:outputText value="#{ApplicationBean.versionInfo}" /></span></p>
			</h:form>
			<a href="http://www.exactprosystems.com">
				<div id="companyLogo"></div>
			</a>
		</div>
	</ui:define>
</ui:composition>

clearth-modules/clearth-gui/src/main/webapp/ui/session_expired.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
		xmlns:ui="http://java.sun.com/jsf/facelets"
		xmlns:h="http://java.sun.com/jsf/html"
		xmlns:f="http://java.sun.com/jsf/core"
		xmlns:p="http://primefaces.org/ui"
		template="../templates/ui.xhtml">
	
	<ui:define name="title">Login</ui:define>
	
	<f:metadata>
		<f:viewParam name="requestUrl" value="#{authBean.requestUrl}" />
		<f:event type="preRenderView" listener="#{authBean.pullValuesFromFlash}"/>
	</f:metadata>
	
	<ui:define name="page">
		<div id="loginContainer">
			<h:form id="loginPanel-expired" rendered="#{ApplicationBean.initializationError == null}">
				<div id="cthLogo" />
				<div id="expired-msg">
					Your session has expired. <br />
					Please re-login to renew your session.
				</div>
				<p:focus context="loginPanel-expired" />
				<p:inputText id="userName" styleClass="authorizeField" value="#{authBean.userName}" autocomplete="off" />
				<p:watermark for="userName" value="Username" />
				<p:password id="password" styleClass="authorizeField" value="#{authBean.password}" feedback="false" />
				<p:watermark for="password" value="Password" />
				<p:commandButton styleClass="loginButton" value="Sign in" action="#{authBean.login}"
						ajax="false" update="loginPanel-expired" />
				<p:messages id="msg" for="loginError" styleClass="loginError" showSummary="false" showDetail="true" />
				<p:effect type="drop" event="load" for="msg" delay="5000">
					<f:param name="mode" value="'hide'" />
					<f:param name="direction" value="'up'" />
				</p:effect>
			</h:form>
			<p:outputPanel id="fatalError" rendered="#{ApplicationBean.initializationError != null}">
				<h:outputText value="#{ApplicationBean.initializationErrorText}" />
			</p:outputPanel>
			<h:form>
				<p style="margin-top: 0px" id="copyright">&copy; 2011-2023 Exactpro Systems, LLC<span style="margin-left: 10px;"><h:outputText value="#{ApplicationBean.versionInfo}" /></span></p>
			</h:form>
			<a href="http://www.exactprosystems.com">
				<div id="companyLogo"></div>
			</a>
		</div>
	</ui:define>
</ui:composition>