clearth-modules/clearth-gui/src/main/java/com/exactprosystems/clearth/web/beans/LogsBean.java
/******************************************************************************
 * Copyright 2009-2022 Exactpro Systems Limited
 * https://www.exactpro.com
 * Build Software to Test Software
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/

package com.exactprosystems.clearth.web.beans;

import com.exactprosystems.clearth.ClearThCore;
import com.exactprosystems.clearth.utils.ExceptionUtils;
import com.exactprosystems.clearth.utils.FileOperationUtils;
import com.exactprosystems.clearth.utils.KeyValueUtils;
import com.exactprosystems.clearth.utils.ThreadDumpGenerator;
import com.exactprosystems.clearth.web.misc.MessageUtils;
import com.exactprosystems.clearth.web.misc.UserInfoUtils;
import com.exactprosystems.clearth.web.misc.WebUtils;

import org.apache.commons.lang.StringUtils;
import org.primefaces.model.StreamedContent;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.*;
import java.util.Map.Entry;
import java.util.regex.Pattern;

import org.apache.logging.log4j.Level;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.core.LoggerContext;
import org.apache.logging.log4j.core.config.Configuration;
import org.apache.logging.log4j.core.config.LoggerConfig;

public class LogsBean extends ClearThBean
{
	private static final String USER_LOG = "User activity log";
	private final File logsDir, outputDir;
	private List<String> selectedLogsList = new ArrayList<>();
	
	private String currentLogger = "";
	private final Map<String, Logger[]> loggers;

	private Set<String> keysForAdmin;
	private Set<String> keysForPowerUser;
	private final Pattern logBackupPattern = Pattern.compile("\\D+\\.log\\.\\d");
	
	public LogsBean() throws IOException
	{
		File dir = WebUtils.getLogsDir();
		if (!dir.exists())
			getLogger().warn("Logs directory '"+dir.getAbsolutePath()+"' doesn't exist");
		
		logsDir = dir;
		outputDir = new File(logsDir, "output/");
		
		String pathToLogConfig = ClearThCore.rootRelative(ClearThCore.configFiles().getCfgDir()+"loggers.cfg");
		Map<String, String> definitions = KeyValueUtils.loadKeyValueFile(pathToLogConfig, false);
		
		loggers = buildLoggersInfo(definitions, pathToLogConfig);
		this.keysForAdmin = new LinkedHashSet<>(this.loggers.keySet());
		this.keysForPowerUser = new LinkedHashSet<>(this.loggers.keySet());
		this.keysForPowerUser.remove(USER_LOG);
	}
	
	
	//*** Logs manipulation routines ***
	
	public List<String> getAllLogsList()
	{
		List<String> result = new ArrayList<>();
		if (logsDir.exists())
		{
			File[] logsFiles = logsDir.listFiles();
			if (logsFiles!=null)
				for (File file : logsFiles)
				{
					if ((!file.isDirectory()) && (!file.getName().equals(".donotdelete")))
						result.add(file.getName());
				}
		}

		Collections.sort(result);

		return result;
	}
	
	public List<String> getSelectedLogsList()
	{
		return selectedLogsList;
	}

	public void setSelectedLogsList(List<String> selectedLogsList)
	{
		this.selectedLogsList = selectedLogsList;
	}

	public void selectAllLogs()
	{
		this.selectedLogsList = getAllLogsList();
	}

	public void deselectAllLogs()
	{
		this.selectedLogsList = Collections.emptyList();
	}

	public StreamedContent getLogsZip()
	{
		if (selectedLogsList.size()==0)
			return null;
		
		if (!logsDir.exists())
			return null;
		
		try
		{
			if (!outputDir.exists())
				outputDir.mkdir();
			
			List<File> filesToZip = new ArrayList<>();
			for (String logName : selectedLogsList)
				filesToZip.add(new File(logsDir, logName));
			File result = new File(outputDir, UserInfoUtils.getUserName()+"_logs.zip");
			FileOperationUtils.zipFiles(result, filesToZip);
			result.deleteOnExit();
			//selectedLogsList.clear();
			return WebUtils.downloadFile(result, "logs.zip");
		}
		catch (Exception e)
		{
			WebUtils.logAndGrowlException("Could not download logs", e, getLogger());
			return null;
		}
	}

	public void clearLogs()
	{
		if (selectedLogsList.size()==0)
			return;

		if (!logsDir.exists())
			return;

		for (String logFileName : selectedLogsList)
		{
			if (isLogBackup(logFileName))
				removeLogBackup(logFileName);
			else
				clearLogFile(logFileName);
		}
	}
	
	
	protected void removeLogBackup(String logFileName)
	{
		Path logPath = Paths.get(logsDir.getAbsolutePath(), logFileName);
		try
		{
			Files.delete(logPath);
			getLogger().info("deleted log file '{}'", logPath);
		}
		catch (IOException e)
		{
			String msg = "Could not delete log file '"+logFileName+"'";
			getLogger().warn(msg, e);
			MessageUtils.addWarningMessage(msg, ExceptionUtils.getDetailedMessage(e));
		}
	}
	
	protected void clearLogFile(String logFileName)
	{
		File logFile = new File(logsDir, logFileName);
		try
		{
			FileOperationUtils.clearFileContent(logFile);
			getLogger().info("cleared log file '{}'", logFile);
		}
		catch (IOException e)
		{
			WebUtils.logAndGrowlException("Could not clear contents of file '"+logFile.getPath()+"'", e, getLogger());
		}
	}
	
	
	protected List<Logger> getLoggersForPackages(String loggerName, String loggerPackages, String pathOfConfig)
	{
		List<Logger> result = new ArrayList<>();
		String[] packages = loggerPackages.split(",");
		for (String loggerPackage : packages)
		{
			Logger loggerObject = LogManager.getLogger(loggerPackage);
			if (loggerObject.getLevel() != null)
				result.add(loggerObject);
			else
				getLogger().error(String.format("Could not get level for logger '%s'. "
								+ "Mapping to non-existing package '%s' or other misconfiguration in file '%s'.", 
						loggerName, loggerObject.getName(), pathOfConfig));
		}
		return result;
	}
	
	protected Map<String, Logger[]> buildLoggersInfo(Map<String, String> definitions, String pathOfConfig)
	{
		Map<String, Logger[]> result = new LinkedHashMap<>();
		for (Entry<String, String> entry : definitions.entrySet())
		{
			List<Logger> loggerObjects = getLoggersForPackages(entry.getKey(), entry.getValue(), pathOfConfig);
			if (!loggerObjects.isEmpty())
				result.put(entry.getKey(), loggerObjects.toArray(new Logger[0]));
		}
		return result;
	}

	private boolean isLogBackup(String logFileName)
	{
		return logBackupPattern.matcher(logFileName).find();
	}
	
	
	//*** Logging level routines ***

	@Deprecated
	public Set<String> getLoggers()
	{
		return this.keysForAdmin;
	}
	
	public Set<String> getLoggers(boolean isAdmin)
	{
		return isAdmin ? this.keysForAdmin : this.keysForPowerUser;
	}
	
	
	public String getCurrentLogger()
	{
		return currentLogger;
	}

	public void setCurrentLogger(String currentLogger)
	{
		if (USER_LOG.equals(currentLogger) && !UserInfoUtils.isAdmin())
		{
			MessageUtils.addErrorMessage("Denied", "You don't have sufficient permissions to change this logger. This incident will be reported.");
			return;
		}
		this.currentLogger = currentLogger;
	}
	
	
	public String getLoggingLevel()
	{
		if (!StringUtils.isEmpty(currentLogger))
			return loggers.get(currentLogger)[0].getLevel().toString();
		else 
			return "<Choose logger>";
	}
	
	public String getAllLoggingLevel()
	{
		int count = 0;
		String lvl = "no loggers";
		for (String key : loggers.keySet())
		{
			if (count == 0)
				lvl = loggers.get(key)[0].getLevel().toString();

			if (!loggers.get(key)[0].getLevel().toString().equals(lvl))
				return "various levels";
			count++;
		}
		return lvl;
	}
	
	public void setLoggingLevel(String lvl)
	{
		Level level = Level.toLevel(lvl);
		LoggerContext ctx = (LoggerContext) LogManager.getContext(false);
		Configuration config = ctx.getConfiguration();
		for (Logger loggerObject : loggers.get(currentLogger))
		{
			LoggerConfig loggerConfig = config.getLoggerConfig(loggerObject.getName());
			loggerConfig.setLevel(level);
		}
		ctx.updateLoggers();
		
		MessageUtils.addInfoMessage("Success", "Level " + lvl + " is now set for '" + currentLogger + "'");
	}
	
	public void setAllLoggingLevels(String lvl)
	{
		Set<String> loggerKeys;

		if (UserInfoUtils.isAdmin())
			loggerKeys = this.keysForAdmin;
		else if (UserInfoUtils.isPowerUser())
			loggerKeys = this.keysForPowerUser;
		else
			loggerKeys = Collections.emptySet();
		
		Level level = Level.toLevel(lvl);
		LoggerContext ctx = (LoggerContext) LogManager.getContext(false);
		Configuration config = ctx.getConfiguration();
		for (String loggerKey : loggerKeys)
		{
			Logger[] logger = loggers.get(loggerKey);
			for (Logger loggerObject : logger)
			{
				LoggerConfig loggerConfig = config.getLoggerConfig(loggerObject.getName());
				loggerConfig.setLevel(level);
			}
		}
		ctx.updateLoggers();
		
		MessageUtils.addInfoMessage("Success", "Level " + lvl + " is now set for all loggers");
	}
	
	public void resetLoggingLevel()
	{
		ClearThCore.getInstance().configureLogging();
	}
	
	public void testLogging()
	{
		Logger[] selectedLoggers;
		if (StringUtils.isEmpty(currentLogger) || (selectedLoggers = loggers.get(currentLogger)) == null)
			return;
		
		for (Logger loggerObject : selectedLoggers)
		{
			org.apache.logging.log4j.Logger lg = LogManager.getLogger(loggerObject.getName()+".Test");
			lg.trace("Logging test at TRACE level");
			lg.debug("Logging test at DEBUG level");
			lg.info ("Logging test at INFO  level");
			lg.warn ("Logging test at WARN  level");
			lg.error("Logging test at ERROR level");
		}
	}

	public File getLogsDir()
	{
		return logsDir;
	}
	
	

clearth-modules/clearth-gui/src/main/java/com/exactprosystems/clearth/web/beans/MaintainBean.java
/******************************************************************************
 * Copyright 2009-2019 Exactpro Systems Limited
 * https://www.exactpro.com
 * Build Software to Test Software
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/

package com.exactprosystems.clearth.web.beans;

import com.exactprosystems.clearth.utils.MemoryAndSpaceMonitor;

public class MaintainBean extends ClearThBean
{
	public void collectGarbage()
	{
		MemoryAndSpaceMonitor.collectGarbage();
	}

	public long getMaxMemory()
	{
		return MemoryAndSpaceMonitor.getMaxMemoryMb();
	}

	public long getTotalMemory()
	{
		return MemoryAndSpaceMonitor.getTotalMemoryMb();
	}

	public long getFreeMemory()
	{
		return MemoryAndSpaceMonitor.getFreeMemoryMb();
	}

	public long getTotalSpace()
	{
		return MemoryAndSpaceMonitor.getTotalSpace(MemoryAndSpaceMonitor.MB_FACTOR);
	}

	public long getFreeSpace()
	{
		return MemoryAndSpaceMonitor.getFreeSpace(MemoryAndSpaceMonitor.MB_FACTOR);
	}

	public long getUsedSpace()
	{
		return MemoryAndSpaceMonitor.getUsedSpace(MemoryAndSpaceMonitor.MB_FACTOR);
	}

	public boolean isMemoryBreachesLimit()
	{
		return MemoryAndSpaceMonitor.isMemoryBreachLimit(90);
	}
}

clearth-modules/clearth-gui/src/main/java/com/exactprosystems/clearth/web/beans/automation/AutomationBean.java
/******************************************************************************
 * Copyright 2009-2019 Exactpro Systems Limited
 * https://www.exactpro.com
 * Build Software to Test Software
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/

package com.exactprosystems.clearth.web.beans.automation;

import com.exactprosystems.clearth.ClearThCore;
import com.exactprosystems.clearth.automation.Scheduler;
import com.exactprosystems.clearth.automation.SchedulersManager;
import com.exactprosystems.clearth.automation.StartAtType;
import com.exactprosystems.clearth.utils.SettingsException;
import com.exactprosystems.clearth.web.beans.ClearThBean;
import com.exactprosystems.clearth.web.beans.ClearThCoreApplicationBean;
import com.exactprosystems.clearth.web.misc.MessageUtils;
import com.exactprosystems.clearth.web.misc.SchedulerEntry;
import com.exactprosystems.clearth.web.misc.UserInfoUtils;
import com.exactprosystems.clearth.web.misc.WebUtils;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.Arrays;
import java.util.List;

@SuppressWarnings({"WeakerAccess", "unused"})
public class AutomationBean extends ClearThBean
{		
	protected final SchedulersManager schedulersManager;
	protected Scheduler selectedScheduler = null;
	protected SchedulerEntry newSchedulerEntry = null;
	
	protected int activeTab = 0;
	protected List<String> schedulersMenu;
	
	protected final AutomationMatrixChecker matrixChecker;

	public AutomationBean()
	{
		this.schedulersManager = ClearThCore.getInstance().getSchedulersManager();
		this.schedulersMenu = createSchedulersMenu();
		this.matrixChecker = createMatrixChecker();
		
		selectScheduler(getDefaultScheduler());
	}
	
	protected List<String> createSchedulersMenu()
	{
		return schedulersManager.getAvailableSchedulerNames(UserInfoUtils.getUserName());
	}

	protected AutomationMatrixChecker createMatrixChecker()
	{
		return new AutomationMatrixChecker();
	}

	public List<String> getSchedulersMenu()
	{
		return schedulersMenu;
	}

	protected Scheduler getDefaultScheduler()
	{
		if (ClearThCore.getInstance().isUserSchedulersAllowed())
			return schedulersManager.getDefaultUserScheduler(UserInfoUtils.getUserName());
		else
			return schedulersManager.getCommonSchedulers().get(0);
	}
	
	public SchedulerEntry getNewSchedulerEntry()
	{
		return this.newSchedulerEntry;
	}
	
	public boolean isAbleToCreateNewScheduler()
	{
		return UserInfoUtils.isAdmin() || (UserInfoUtils.isPowerUser() && isUserSchedulersAllowed());
	}
	
	public boolean isUserSchedulersAllowed()
	{
		return ClearThCore.getInstance().isUserSchedulersAllowed();
	}
	
	public void createNewScheduler()
	{
		newSchedulerEntry = new SchedulerEntry(UserInfoUtils.isAdmin(), UserInfoUtils.isPowerUser() ? UserInfoUtils.getUserName() : "", "");
	}
	
	public void saveNewScheduler()
	{
		// Check permissions for creating new scheduler
		if (!isAbleToCreateNewScheduler() || (UserInfoUtils.isPowerUser() && newSchedulerEntry.isCommon()))
		{
			MessageUtils.addErrorMessage("Permission denied", "You are not allowed to create new scheduler");
			return;
		}
		
		try
		{
			schedulersManager.addScheduler(newSchedulerEntry.isCommon() ? SchedulersManager.COMMON_SCHEDULERS_KEY : newSchedulerEntry.getForUser(), 
					newSchedulerEntry.getName());
			schedulersMenu = createSchedulersMenu();
			WebUtils.addCanCloseCallback(true);
		}
		catch (SettingsException e)
		{
			MessageUtils.addErrorMessage("Error", e.getMessage());
		}
		catch (Exception e)
		{
			String errorMsg = "Could not init new user scheduler";
			getLogger().error(errorMsg, e);
			MessageUtils.addErrorMessage("Error", errorMsg);
		}
	}
	
	public void onTimer()
	{
	}
	
	public int getActiveTab()
	{
		return activeTab;
	}
	
	public void setActiveTab(int activeTab)
	{
		this.activeTab = activeTab;
	}
	
	public void selectScheduler(Scheduler scheduler)
	{
		this.selectedScheduler = scheduler;
		this.matrixChecker.setSelectedScheduler(scheduler);
		this.matrixChecker.resetCheckedMatricesErrors();
	}
	
	public void setScheduler(String scheduler)
	{
		selectScheduler(schedulersManager.getSchedulerByName(scheduler, UserInfoUtils.getUserName()));
	}
	
	public String getScheduler()
	{
		return selectedScheduler.getName();
	}

	public Scheduler getSelectedScheduler()
	{
		return selectedScheduler;
	}
	

	/**
	 @deprecated . Use getAppContextPath() in ApplicationBean;
	 */
	@Deprecated
	public String getAppContextPath()
	{
		return ClearThCoreApplicationBean.getInstance().getAppContextPath();
	}

	public List<String> getStartAtTypes()
	{
		return Arrays.asList(StartAtType.END_STEP.getStringType(), StartAtType.START_STEP.getStringType(),
				StartAtType.START_SCHEDULER.getStringType(), StartAtType.START_EXECUTION.getStringType());
	}

	public String safeFileName(String value)
	{
		try
		{
			return URLEncoder.encode(value, "UTF-8").replace("+", "%20");
		}
		catch (UnsupportedEncodingException e)
		{
			return null;
		}
	}

	public AutomationMatrixChecker getMatrixChecker() {
		return matrixChecker;
	}
}

clearth-modules/clearth-gui/src/main/webapp/ui/restricted/home.xhtml
<ui:composition xmlns="http://www.w3c.org/1999/xhtml"
		xmlns:ui="http://java.sun.com/jsf/facelets"
		xmlns:h="http://java.sun.com/jsf/html"
		xmlns:f="http://java.sun.com/jsf/core"
		xmlns:p="http://primefaces.org/ui"
		xmlns:c="http://java.sun.com/jsp/jstl/core"
		template="../../templates/restricted.xhtml">
		
	<ui:define name="title">Home</ui:define>

	<ui:define name="content">
	<div id="homeWrapper">
		<div id="homeBlock">
			<span class="title">Welcome to ClearTH</span>
			<br />
			ClearTH provides various features: test automation, connections to system gateways, converters, etc.<br/>
			Please select needed function from the menu on the left:
			<ul style="margin-top: 5px;">
				<li>Automation - run automated tests and see history of the launches including detailed reports.</li>
				<c:if test="${userBean.admin || userBean.powerUser}"><li>Connectivity - setup connections to system gateways.</li></c:if>
				<li>ClearTH logs - download ClearTH logs and setup the verbosity of the loggers.</li>
				<li>Tools - miscellaneous helpers like message parser, message to script converter, etc.</li>
				<c:if test="${userBean.admin || userBean.powerUser}"><li>User management - administration of ClearTH users.</li></c:if>
				<li>Recent pop-ups - list of pop-up messages that were shown recently in case you have missed them.</li>
				<li>Roll up - button to toggle compact view of the menu.</li>
				<li>Sign out - log out from the application and return to log-in page.</li>
			</ul>
		</div>
	</div>
	</ui:define>
</ui:composition>

clearth-modules/clearth-gui/src/main/webapp/ui/restricted/maintain.xhtml
<ui:composition xmlns="http://www.w3c.org/1999/xhtml"
		xmlns:ui="http://java.sun.com/jsf/facelets"
		xmlns:h="http://java.sun.com/jsf/html"
		xmlns:f="http://java.sun.com/jsf/core"
		xmlns:p="http://primefaces.org/ui"
		xmlns:c="http://java.sun.com/jsp/jstl/core"
		template="../../templates/restricted.xhtml">
	
	<ui:define name="title">Maintain</ui:define>

	<ui:define name="content">
		<label class="pageTitle">ClearTH maintenance</label>
		<div class="entry">
			<h:form id="Memory">
				<h2>Memory info</h2>
				<h:outputText value="Maximum memory: " />
				<h:outputText value="#{maintainBean.maxMemory} Mb" />
				<br />
				<h:panelGroup id="memoryInfo">
					<h:outputText value="Total memory currently available: " />
					<h:outputText value="#{maintainBean.totalMemory} Mb" />
					<br />
					<h:outputText value="Free memory: " />
					<h:outputText value="#{maintainBean.freeMemory} Mb"
							style="#{maintainBean.isMemoryBreachesLimit() ? 'color: red;' : ''}"/>
					<br />
					<br />
					Please note that total amount of available memory can be increased by automatic request of Java VM if more memory is needed by ClearTH. After that amount of free memory will be increased as well.
					<br />
					If you see that all free memory is about to be consumed and total amount of memory isn't increasing anymore you can ask Java VM to run Garbage collector for ClearTH. It will force freeing of unused memory.
					<br />
					<br />
					<p:commandButton value="Run Garbage collector" actionListener="#{maintainBean.collectGarbage}" update=":Memory" />
					<br />
					<br />
				</h:panelGroup>
				<p:poll interval="5" update="memoryInfo" global="false"/>
			</h:form>
			<h:form id="Disk">
				<h2>Disk info</h2>
				<h:outputText value="Total space: " />
				<h:outputText value="#{maintainBean.totalSpace} Mb" />
				<br />
				<h:panelGroup id="spaceInfo">
					<h:outputText value="Free space: " />
					<h:outputText value="#{maintainBean.freeSpace} Mb" />
					<br />
					<br />
				</h:panelGroup>
				<p:poll interval="15" update="spaceInfo" global="false"/>
			</h:form>
		</div>
	</ui:define>
</ui:composition>

clearth-modules/clearth-gui/src/main/webapp/ui/restricted/mvel_helper.xhtml
<ui:composition xmlns="http://www.w3c.org/1999/xhtml"
				xmlns:ui="http://java.sun.com/jsf/facelets"
				xmlns:h="http://java.sun.com/jsf/html"
				xmlns:f="http://java.sun.com/jsf/core"
				xmlns:p="http://primefaces.org/ui">
	
	<p:selectOneButton value="#{mvelHelperBean.activeTab}" style="margin: 8px 0px 5px 0px;">
		<p:ajax update="ExpCalc:outputHelperPanel"/>
		<f:selectItem itemLabel="Functions" itemValue="0" />
		<f:selectItem itemLabel="Patterns" itemValue="1" />
		<f:selectItem itemLabel="Special" itemValue="2" />
	</p:selectOneButton>
	<p:outputPanel id="outputHelperPanel" style="height:80%;">
		<p:outputPanel rendered="#{mvelHelperBean.activeTab == 0}" style="height:100%;">
			<div class = "treeTable" style="display:flex; flex-direction: row; justify-content:space-between; align-items:stretch; height:100%;">
				<div style="width:42%; display:flex; flex-direction: column;">
					<div style="height:100%; overflow-y:auto; overflow-x:auto; border: 1px solid #ECEFF1; border-radius:3px">
						<p:tree value="#{mvelHelperBean.methodsTreeRoot}" var="node" selectionMode="single" selection="#{mvelHelperBean.selectedMethodNode}"
								style="border:none; height:90%">
							<p:ajax event="select" update=":ExpCalc:methodInfo" listener="#{mvelHelperBean.onMethodNodeSelect}" />
							<p:treeNode type="group" style="width:100%">
								 <span style="cursor: pointer; width:100%;" onclick="this.parentNode.parentNode.children[0].click();">
									 <b><h:outputText value="#{node}"/></b>
								</span>
							</p:treeNode>
							<p:treeNode type="method">
								<h:outputText value="#{node.name} (#{node.args})"/>
							</p:treeNode>
						</p:tree>
					</div>
				</div>
				<div style="width:56%">
					<p:outputPanel id="methodInfo">
						<p:panel rendered="#{mvelHelperBean.selectedMethodNode != null}"
								style="width:100%; height: 100%; padding:0px; overflow-y:auto;" styleClass="greyHeader">
							<f:facet name="header">
								<b>
									#{mvelHelperBean.selectedMethodData.name}
									<span style="color:#616161">(#{mvelHelperBean.selectedMethodData.args})</span>
									return
									<span style="color:#616161">#{mvelHelperBean.selectedMethodData.returnType}</span>
								</b>
							</f:facet>
							<p style="text-align: justify;">
								<h:outputText value="#{mvelHelperBean.selectedMethodData.description}"/>
							</p>
							<p>
								<b>Usage:</b>
							</p>
							<div style="display:inline-flex; flex-direction:row;">
								<ui:repeat value="#{mvelHelperBean.selectedMethodData.usage}" var="usg">
									<div style="display:flex; flex-direction:row; justify-content:space-between; margin-right:40px">
										<div>
											<p:commandButton styleClass="smallButton" icon="ui-icon-copy" update=":ExpCalc:inputExpr_textArea"
													 actionListener="#{ecToolBean.copyUsage(usg)}" style="margin-right: 8px;"/>
										</div>
										<div>
											#{usg}
										</div>
									</div>
								</ui:repeat>
							</div>
						</p:panel>
					</p:outputPanel>
				</div>
			</div>
		</p:outputPanel>
		<p:outputPanel rendered="#{mvelHelperBean.activeTab == 1}" style="border: none;">
			<p:accordionPanel activeIndex="null">
				<p:tab title="Date and Time Patterns">
					<ui:include src="help/date_and_time_patterns.xhtml"/>
				</p:tab>
				<p:tab title="Escape Characters">
					<ui:include src="help/escape_characters.xhtml"/>
				</p:tab>
			</p:accordionPanel>
		</p:outputPanel>
		<p:outputPanel rendered="#{mvelHelperBean.activeTab == 2}" style="height:100%;">
			<ui:include src="help/special_data.xhtml"/>
		</p:outputPanel>
	</p:outputPanel>
</ui:composition>